<script lang="ts">
const loadPropertyData = () => new Promise<Record<string, any>[]>((resolve, reject) => {
	setTimeout(() => {
		resolve([{}])
	}, 3000)
})
</script>


<script setup lang="ts">
const data = await loadPropertyData()


</script>
<template>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
	<h2>{{ $t('about') }}</h2>
</template>
